routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//routes connexion

Route::get('/bonjour-professeur', function(){
    return view('Professeur.bonjour-professeur');
});

Route::get('/bonjoureleves', function(){
    return view('Eleves.bonjoureleve');
});

//routes messagerie
//fonction visible dans le controlleur conversations nom de la fonction index//
//Route::get('/home', 'ConversationsController@index')->name('home');
//fonction visible dans le controlleur conversations nom de la fonction index//
Route::get('/messagerie', 'ConversationsController@index')->name('messagerie');
//fonction visible dans le controlleur conversations nom de la fonction show//
Route::get('/conversations/{user}', 'ConversationsController@show')->name('conversations.show');


//fin routes messagerie



Route::get('/bonjour-parent', function(){
    return view('Parent.bonjour-parent');
});

Route::get('/mon-planning', function(){
    return view('Professeur.mon-planning');
});

Route::get('/mes-documents-parent', function(){
    return view('Parent.mes-documents-parent');
});

Route::get('/', function () {
    return view('auth/login');
});

Route::get('/home', function () {
    return view('auth/home');
});

//route admin

Route::get('/bonjour-admin', function(){
    return view('admin.users.bonjour-admin');
});

Route::get('/mon-profiladmin', function () {
    return view('admin/users/mon-profiladmin');
});

Route::get('/gestionecoles', function () {
    return view('admin/users/les-ecoles');
});

Route::get('/gestioneleves', function () {
    return view('admin/users/les-eleves');
});

Route::get('/gestioninstruments', function () {
    return view('admin/users/les-instruments');
});

//Route::get('/gestionevenements', function () {
    //return view('admin.users.les-evenements');
//});

//Affichage evenement dans la view les-evenements:
Route::get('/les-evenements', function () {
    $events = App\Event::all();
    return view('admin.users.les-evenements', compact('events'));
});

Route::get('/gestionecoles', function () {
    $ecoles = App\Ecole::all();
    return view('admin.users.les-ecoles', compact('ecoles'));
});

Route::get('/gestioninstruments', function () {
    $instruments = App\Instruments::all();
    return view('admin.users.les-instruments', compact('instruments'));
});

//fin routes admin

//routes commune parent/prof/élèves

Route::get('/mon-profil', function () {
    return view('mon-profil');
});

Route::get('/evenement', function () {
    return view('evenement');
});

Route::get('/mes-documents', function () {
    return view('mes-documents');
});

//fin routes commune

//route eleves

Route::get('/mes-cours', function () {
    return view('mes-cours');
});

Route::get('/bonjoureleve', function () {
    return view('Eleves/bonjoureleve');
});

Route::get('/parenteleve', function () {
    return view('Parent/parenteleve');
});

Route::get('/absence-retard', function () {
    return view('Parent/absence-retard');
});

Route::get('/mes-enfants', function () {
    return view('Parent/enfants-parents');
});

Route::get('/partitions', function () {
    return view('partition');
});

Route::get('/reglement', function () {
    return view('reglement');
});

Route::get('/autres-documents', function () {
    return view('/autre-documents');
});


//fin routes eleves

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/admin/users', 'Admin\UsersController');
Route::resource('/admin/users', 'Admin\EcolesController');


//route gestion des administrateur namespace admin car controller dans le dossier admin
Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
    Route::resource('users', 'UsersController');
});

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
    Route::resource('ecoles', 'ecolesController');
});

//Route::get('event/{event}', 'EventController@edit')->name('event');

//Route::get('/Admin', "Admin\UsersController");

//Disconnected
Route::get('/logout', "Auth\LoginController@logout");

Route::get('/register', function () {
    return view('Auth/register');
});




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//redirection part rapport au roles utilisateurs:
Route::get('user/{id}', 'Auth\LoginController@redirectTo');

//formulaire creation evenements:

Route::get('/events/create', 'EventController@create')->name('events.create');
Route::post('/events/destroy/{id}', 'EventController@destroy')->name('events.destroy');
Route::post('/events', 'EventController@store')->name('events.store');

Route::get('/Eleves/create', 'ElevesController@create')->name('Eleves.create');
Route::post('/Eleves/destroy/{id}', 'ElevesController@destroy')->name('Eleves.destroy');
Route::post('/Eleves', 'ElevesController@store')->name('Eleves.store');

Route::post('/partition', 'DocumentController@store')->name('partition.store');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'surname','password','numero_telephone','date_entree',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles()
    {
        return $this->belongsToMany('App\Role');
    }

    public function conversations()
    {
        return $this->belongsToMany('App\Conversation');
    }

    public function isAdmin()
    {
        return $this->roles()->where('name', 'admin')->first();
    }

    public function HasAnyRole(array $roles)
    {
        return $this->roles()->whereIn('name', $roles)->first();
    }
    public function events()
    {
        return $this->hasMany('App\Event')->orderBy('created_at', 'DESC');
    }

    public function cours()
    {
        return $this->belongsToMany('App\Cour');
    }

    public function instruments()
    {
        return $this->belongsToMany('App\Instrument');
    }

    public function ecoles()
    {
        return $this->belongsToMany('App\Ecole');
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use App\Role;
use Illuminate\Support\Facades\Gate;

class UsersController extends Controller
{
    public function construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('admin.users.utilisateurs')->with('users', $users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        if (Gate::denies('edit-users')) {

            return redirect()->route('admin.users.utilisateurs');
    }


        $roles = Role::all();

        return view('admin.users.edit',[
            'user' => $user,
            'roles' => $roles

        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->roles()->sync($request->roles);
        $user->name = $request->name;
        $user->email = $request->email;
        $user->save();

        return redirect()->route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        if (Gate::denies('delete-users')) {

            return redirect('admin.users.index');
        }

        $user->roles()->detach();
        $user->delete();

        return redirect()->route('admin.users.index');
    }
}

resources/views/admin/users/bonjour-admin.blade.php
@extends('layouts.app')

@section('navbar')
@include('include.navbar')
@endsection

@section('content')
@include('include.bouton-bonjour')
        <div class="flex flex-col items-center">
        <a href="/mon-profiladmin"><button class="mt-12 bg-indigo-200 text-black text-2xl font-bold py-2 px-4 rounded-full w-56 h-15" type="button">Mon profil</button></a>
        <div class="flex flex-col items-center">
        <a class="dropdowm-item flex flex-col items-center hover:no-underline" href="{{ route("admin.users.index") }}">
    <button class="mt-12 bg-indigo-200 text-black text-2xl font-bold py-2 px-4 rounded-full w-auto h-15" >
            Gestion des utilisateurs
    </button>
        <div class="flex flex-col items-center">
        <a href="/gestionecoles"><button class="mt-12 bg-indigo-200 text-black text-2xl font-bold py-2 px-4 rounded-full w-auto h-15" type="button">Gestion des écoles</button></a>
        </div>
        <div class="flex flex-col items-center">
                <a href="/gestioneleves"><button class="mt-12 bg-indigo-200 text-black text-2xl font-bold py-2 px-4 rounded-full w-auto h-15" type="button">Gestion des élèves</button></a>
        </div>
        <div class="flex flex-col items-center">
                <a href="/gestioninstruments"><button class="mt-12 bg-indigo-200 text-black text-2xl font-bold py-2 px-4 rounded-full w-auto h-15" type="button">Gestion des instruments</button></a>
        </div>
        <div class="flex flex-col items-center">
                <a href="/les-evenements"><button class="mt-12 bg-indigo-200 text-black text-2xl font-bold py-2 px-4 rounded-full w-auto h-15" type="button">Les évènements</button></a>
        </div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('navbar')
@include('include.navbar')
@endsection

@section('content')
<div class="flex flex-col items-center">
    <button class="mt-8 bg-red-800 text-white text-3xl font-bold py-2 px-4 rounded-full w-auto h-15 cursor-default" type="text" disabled="disabled">Modifier <strong>{{ $user->name}}</strong></button>
</div>
<div class="flex flex-col items-center">
        <form action="{{ route('admin.users.update', $user) }}" method="POST">
            @csrf
            @method('PATCH')
            <div class="form-group row mt-8">
                <label for="email" class="cold-md-6 col-form-label">{{__('Adresse mail') }}</label>
                <div class="col-md-12">
                    <input id="email" type="email" class="form-control 
                    
                    @error('email') is-invalid 
                    
                    @enderror
                    "name="email" value="{{ old('email') ?? $user->email }}" requiere autocomplete="email" autofocus>

                    @error('email')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>
            <label for="name" class="cold-md-6 col-form-label">{{__('Nom') }}</label>

                <div class="col-md-12">
                    <input id="name" type="text" class="form-control 
                    
                    @error('name') is-invalid 
                    @enderror"
                    name="name" value="{{ old('name') ?? $user->name }}" requiered autocomplete="name" autofocus>

                    @error('name')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            <div class="flex flex-col items-center">
            @foreach ($roles as $role)
                <div class="form-group form-check mt-8">
                    <input type="checkbox" class="form-check-input" name="roles[]" 
                    value="{{ $role->id }}" id="{{ $role->id }}" 
                    @if($user->roles->pluck('id')->contains($role->id))checked
                    @endif>
                    <label for ="{{ $role->id }}" class="form-check-label">{{ $role->name }}</label>
                </div>
            @endforeach
            </div>
        <button type="submit" class="m-2 mt-0 bg-blue-900 text-white text-xl font-bold py-1 px-3 rounded-full w-auto h-auto">Modifier les informations</button>
        </form>
</div>
@endsection

resources/views/admin/users/les-ecoles.blade.php
@extends('layouts.app')

@section('navbar')
@include('include.navbar')
@endsection

@section('content')
<div class="flex flex-col items-center">
    <button class="mt-8 bg-red-800 text-white text-3xl font-bold py-2 px-4 rounded-full w-auto h-15 cursor-default" type="text" disabled="disabled">Liste des écoles</button>
    <tbody class="flex-1 sm:flex-none">
        <div class="flex items-center justify-center">
            <div class="container">
        <table class="mt-8 text-black w-full flex flex-row flex-no-wrap sm:bg-white rounded-lg overflow-hidden sm:shadow-lg my-5">
            <thead class="text-white">
                @foreach ($ecoles as $ecole)
                <tr class="bg-blue-900 flex flex-col flex-no wrap sm:table-row rounded-l-lg sm:rounded-none mb-2 sm:mb-0">
                    <th class="p-3 text-left">#</th>
                    <th class="p-3 text-left">Nom</th>
                    <th class="p-3 text-left">Lieu</th>
                    {{-- <th class="p-3 text-left">Rôles</th>
                    <th class="p-3 text-left py-4" width="110px">Action</th> --}}
                </tr>
                @endforeach
            </thead>
                @foreach ($ecoles as $ecole)
                    <tr class="flex flex-col flex-no wrap sm:table-row mb-2 sm:mb-0">
                        <td class="border-grey-light border hover:bg-gray-100 p-3">{{ $ecole->id }}</td>
                        <td class="border-grey-light border hover:bg-gray-100 p-3">{{ $ecole->name }}</td>
                        <td class="border-grey-light border hover:bg-gray-100 p-3">{{ $ecole->lieu}}</td>
                        {{-- <td class="border-grey-light border hover:bg-gray-100 p-3 truncate">{{ $user->email}}</td>
                        <td class="border-grey-light border hover:bg-gray-100 p-3">{{ implode(', ', $user->roles()->get()->pluck('name')->toArray()) }}</td> --}}
    
                        {{-- <td class="border-grey-light border hover:bg-gray-100 text-red-400 hover:text-red-600 hover:font-medium cursor-pointer p-3">
                            <div class="flex mt-1">
                            <a href="{{ route('ecoles.edit', $ecole->id)}}">
                                <button type="submit" >
                                    <i class="far fa-edit"></i>
                                </button>
                            </a>
    
                            <form action="{{ route('ecoles.destroy',$ecole->id)}}" method="POST" class="ml-5">
                                @csrf
                                @method('DELETE')
                                <button type="submit" onclick="return confirm('Voulez vous supprimer cette ecoles ?')">
                                    <i class="fas fa-trash-alt"></i>
                                </button>
                            </form>
                            </div>
                        </td>
                    </tr>
                </div> --}}
                @endforeach
            </tbody>
        </table> 
    @endsection
    <style>
        html,
        body {
            height: 100%;
        }
    
        @media (min-width: 640px) {
        table {
            display: inline-table !important;
        }
    
        thead tr:not(:first-child) {
            display: none;
        }
        }
    
        td:not(:last-child) {
            border-bottom: 0;
        }
    
        th:not(:last-child) {
            border-bottom: 2px solid rgba(0, 0, 0, .1);
        }
    
    </style>

resources/views/admin/users/les-eleves.blade.php
@extends('layouts.app')

@section('navbar')
@include('include.navbar')
@endsection

@section('content')
<div class="flex flex-col items-center">
    <button class="mt-8 bg-red-800 text-white text-3xl font-bold py-2 px-4 rounded-full w-auto h-15 cursor-default" type="text" disabled="disabled">Liste des élèves</button>
    <table class="mt-8 table-auto text-black">
        <thead>
            <tr>
            <th class="px-4 py-2">#</th>
            <th class="px-4 py-2">Nom</th>
            <th class="px-4 py-2">Mail</th>
            </tr>
        </thead>
        <tbody>
            
            <tr>
            <td class="border px-4 py-4"></td>
            <td class="border px-4 py-4"></td>
            <td class="border px-4 py-4"></td>
            <td class="border px-4 py-4"></td>
            <td>
            <a href="#"><button class="m-2 mt-0 bg-blue-900 text-white text-xl font-bold py-1 px-3 rounded-full w-auto h-auto" type="text">Editer</button></a>
            <form action="#" method="POST" class="d-inline">
                @csrf
                @method('DELETE')
                <button type="submit" class="m-2 mt-0 bg-red-800 text-white text-xl font-bold py-1 px-2 rounded-full w-auto h-auto">Supprimer</button>
            </form>
            </td>
            </tr>
            
        </tbody>
        </table> 
</div>
@endsection

resources/views/admin/users/les-evenements.blade.php
@extends('layouts.app')

@section('navbar')
@include('include.navbar')
@endsection

@section('content')
<div class="flex flex-col items-center">
    <button class="mt-8 bg-red-800 text-white text-3xl font-bold py-2 px-4 rounded-full w-auto h-15 cursor-default" type="text" disabled="disabled">Liste des évènements</button></div>
</div>
@if (Auth::user()->roles->pluck('name')->contains('admin_membre_conseil'))
        <div class="flex flex-col items-center">
            <a href="{{route('events.create')}}"><button class="mt-8 bg-blue-900 text-white text-xl font-bold py-1 px-3 rounded-full w-auto h-auto"type="text">
            Créer un évènement
        </button></a>
        </div>   
@endif
<div class="flex items-center justify-center ml-auto mt-10">
        <div class="flex flex-wrap mx-2">
        @foreach ($events as $event)
            <div class="flex flex-wrap -mx-1 lg:-mx-4">
            <div class="flex -mx-3">
            <div class="px-6 py-0">
            <table class="w-full mt-8 text-black flex flex-row flex-no-wrap sm:bg-white rounded-lg overflow-hidden sm:shadow-lg my-5">
        <div class="max-w-sm rounded overflow-hidden shadow-lg ml-auto m-3">
            <img class="w-full mb-0" src="{{ asset('/storage') . '/' . $event->image }}" class="w-30" alt="{{ $event->name }}">
            <div class="py-4">
            <div class="font-bold text-xl mb-0 text-center"><h1>{{ $event->name }}</h1></div>
            <p class="text-gray-700 text-base text-center">
                {{ $event->caption }}
            </p>
            </div>
            <div class="py-4 flex items-center justify-center">
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2">{{ $event->lieu }}</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2">{{ $event->date_event }}</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2">{{ $event->heure_event }}</span>
            </div>
            @if (Auth::user()->roles->pluck('name')->contains('admin_membre_conseil'))
            <div class="flex flex-col items-center">
            <form action="{{ route ('events.destroy',$event->id)}}" method="POST" class="ml-5">
                @csrf
                @method('POST')
                <!--{{ method_field('delete') }}-->
                <button type="submit" onclick="return confirm('Voulez vous supprimer cet évènement ?')">
                    <i class="fas fa-trash-alt"></i>
                </button>
            </form>
            </div>
            @endif
            </table>
                </div>
            </div>
            </div>
        @endforeach
        </div>
    </div>
</div>
    </div>
@endsection

resources/views/admin/users/les-instruments.blade.php
@extends('layouts.app')

@section('navbar')
@include('include.navbar')
@endsection

@section('content')
<div class="flex flex-col items-center">
    <button class="mt-8 bg-red-800 text-white text-3xl font-bold py-2 px-4 rounded-full w-auto h-15 cursor-default" type="text" disabled="disabled">Liste des instruments</button>
    <tbody class="flex-1 sm:flex-none">
        <div class="flex items-center justify-center">
            <div class="container">
        <table class="mt-8 text-black w-full flex flex-row flex-no-wrap sm:bg-white rounded-lg overflow-hidden sm:shadow-lg my-5">
            <thead class="text-white">
                @foreach ($instruments as $instrument)
                <tr class="bg-blue-900 flex flex-col flex-no wrap sm:table-row rounded-l-lg sm:rounded-none mb-2 sm:mb-0">
                    <th class="p-3 text-left">#</th>
                    <th class="p-3 text-left">Nom</th>
                    {{-- <th class="p-3 text-left">Lieu</th> --}}
                    {{-- <th class="p-3 text-left">Rôles</th>
                    <th class="p-3 text-left py-4" width="110px">Action</th> --}}
                </tr>
                @endforeach
            </thead>
                @foreach ($instruments as $instrument)
                    <tr class="flex flex-col flex-no wrap sm:table-row mb-2 sm:mb-0">
                        <td class="border-grey-light border hover:bg-gray-100 p-3">{{ $instrument->id }}</td>
                        <td class="border-grey-light border hover:bg-gray-100 p-3">{{ $instrument->name }}</td>
                        {{-- <td class="border-grey-light border hover:bg-gray-100 p-3">{{ $ecole->lieu}}</td> --}}
                        {{-- <td class="border-grey-light border hover:bg-gray-100 p-3 truncate">{{ $user->email}}</td>
                        <td class="border-grey-light border hover:bg-gray-100 p-3">{{ implode(', ', $user->roles()->get()->pluck('name')->toArray()) }}</td> --}}
    
                        {{-- <td class="border-grey-light border hover:bg-gray-100 text-red-400 hover:text-red-600 hover:font-medium cursor-pointer p-3">
                            <div class="flex mt-1">
                            <a href="{{ route('ecoles.edit', $ecole->id)}}">
                                <button type="submit" >
                                    <i class="far fa-edit"></i>
                                </button>
                            </a>
    
                            <form action="{{ route('ecoles.destroy',$ecole->id)}}" method="POST" class="ml-5">
                                @csrf
                                @method('DELETE')
                                <button type="submit" onclick="return confirm('Voulez vous supprimer cette ecoles ?')">
                                    <i class="fas fa-trash-alt"></i>
                                </button>
                            </form>
                            </div>
                        </td>
                    </tr>
                </div> --}}
                @endforeach
            </tbody>
        </table> 
    @endsection
    <style>
        html,
        body {
            height: 100%;
        }
    
        @media (min-width: 640px) {
        table {
            display: inline-table !important;
        }
    
        thead tr:not(:first-child) {
            display: none;
        }
        }
    
        td:not(:last-child) {
            border-bottom: 0;
        }
    
        th:not(:last-child) {
            border-bottom: 2px solid rgba(0, 0, 0, .1);
        }
    
    </style>

resources/views/admin/users/mon-profiladmin.blade.php
@extends('layouts.app')

@section('navbar')
@include('include.navbar')
@endsection

@section('content')
<div class="flex flex-col items-center">
<button class="mt-8 bg-red-800 text-white text-3xl font-bold py-2 px-4 rounded-full w-64 h-15 cursor-default" type="text" disabled="disabled" name="mon profil">Mon profil</button>
    </div>
    <div class="-m-2 flex justify-center p-12 text-2xl text-black font-extrabold">Statut :
    </div>
    <div class="flex flex-col items-center">
<button class="-m-6 bg-indigo-200 text-black text-2xl font-bold py-2 px-4 rounded-full w-auto h-15 cursor-default" disabled="disabled" type="button" name="statut">{{ Auth::user()->roles->pluck('name') }}</button></a>
    </div>
<div class="flex justify-center p-12 text-2xl text-black font-extrabold">Prénom :
    </div>
    <div class="flex flex-col items-center">
<button class="-m-6 bg-indigo-200 text-black text-2xl font-bold py-2 px-4 rounded-full w-auto h-15 cursor-default" disabled="disabled" type="button" name="Prénom">{{ Auth::user()->surname }}</button>
    </div>
<div class="flex justify-center p-12 text-2xl text-black font-extrabold">E-mail :</div>
    <div class="flex flex-col items-center">
<button class="-m-6 bg-indigo-200 text-black text-2xl font-bold py-2 px-4 rounded-full w-auto h-15 cursor-default" disabled="disabled" type="button" name="email">{{ Auth::user()->email }}</button>
    </div>
    <!--<div class="flex justify-center p-12 text-2xl text-black font-extrabold">Numéro de téléphone :
    </div>
    <div class="flex flex-col items-center">
<button class="-m-6 bg-indigo-200 text-black text-2xl font-bold py-2 px-4 rounded-full w-56 h-15 cursor-default" disabled="disabled" type="button" name="telephone">00.00.00.00.00</button>
    </div>-->
        <a href="{{route('logout')}}" class="flex flex-col items-center hover:no-underline">
            <button class="flex justify-center mt-12 bg-red-800 text-white text-xl font-bold py-2 px-4 rounded-full w-54 h-15" >
                Déconnexion
            </button>
        </a>
    </div>
@endsection

resources/views/admin/users/utilisateurs.blade.php
@extends('layouts.app')

@section('navbar')
@include('include.navbar')
@endsection

@section('content')
<div class="flex flex-col items-center">
    <button class="mt-8 bg-red-800 text-white text-3xl font-bold py-2 px-4 rounded-full w-auto h-15 cursor-default" type="text" disabled="disabled">Liste des utilisateurs</button></div>
    <tbody class="flex-1 sm:flex-none">
    <div class="flex items-center justify-center">
        <div class="container">
    <table class="mt-8 text-black w-full flex flex-row flex-no-wrap sm:bg-white rounded-lg overflow-hidden sm:shadow-lg my-5">
        <thead class="text-white">
            @foreach ($users as $user)
            <tr class="bg-blue-900 flex flex-col flex-no wrap sm:table-row rounded-l-lg sm:rounded-none mb-2 sm:mb-0">
                <th class="p-3 text-left">#</th>
                <th class="p-3 text-left">Nom</th>
                <th class="p-3 text-left">Email</th>
                <th class="p-3 text-left">Rôles</th>
                <th class="p-3 text-left py-4" width="110px">Action</th>
            </tr>
            @endforeach
        </thead>
            @foreach ($users as $user)
                <tr class="flex flex-col flex-no wrap sm:table-row mb-2 sm:mb-0">
                    <td class="border-grey-light border hover:bg-gray-100 p-3">{{ $user->id }}</td>
                    <td class="border-grey-light border hover:bg-gray-100 p-3">{{ $user->surname}}</td>
                    <td class="border-grey-light border hover:bg-gray-100 p-3 truncate">{{ $user->email}}</td>
                    <td class="border-grey-light border hover:bg-gray-100 p-3">{{ implode(', ', $user->roles()->get()->pluck('name')->toArray()) }}</td>

                    <td class="border-grey-light border hover:bg-gray-100 text-red-400 hover:text-red-600 hover:font-medium cursor-pointer p-3">
                        <div class="flex mt-1">
                        <a href="{{ route('admin.users.edit', $user->id)}}">
                            <button type="submit" >
                                <i class="far fa-edit"></i>
                            </button>
                        </a>

                        <form action="{{ route ('admin.users.destroy',$user->id)}}" method="POST" class="ml-5">
                            @csrf
                            @method('DELETE')
                            <button type="submit" onclick="return confirm('Voulez vous supprimer ce profil ?')">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                        </form>
                        </div>
                    </td>
                </tr>
            </div>
            @endforeach
        </tbody>
    </table> 
@endsection
<style>
    html,
    body {
        height: 100%;
    }

    @media (min-width: 640px) {
    table {
        display: inline-table !important;
    }

    thead tr:not(:first-child) {
        display: none;
    }
    }

    td:not(:last-child) {
        border-bottom: 0;
    }

    th:not(:last-child) {
        border-bottom: 2px solid rgba(0, 0, 0, .1);
    }

</style>